x-base-config: &base
    build:
        context: .
        dockerfile: docker/.Dockerfile
    environment:
        REDIS_HOST: redis
    networks:
        - dpf_network
    depends_on:
        - redis
    restart: always

services:
    # database for jobs and queues
    redis:
        image: redis:latest
        volumes:
            - ./redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - dpf_network
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping" ]
            interval: 10s
            timeout: 8s
            retries: 5

    # dashboard to monitor jobs
    rq-dashboard:
        <<: *base
        command: dashboard
        ports:
            - "9181:9181"

    # worker to run jobs
    rq-worker:
        <<: *base
        command: worker
        volumes:
            - ./jobs:/app/jobs
        deploy:
            mode: replicated
            replicas: 1
            endpoint_mode: vip

networks:
    dpf_network:
