services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        networks:
            - dpf_network
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
            interval: 10s
            timeout: 8s
            retries: 5
    redis:
        image: redis:latest
        volumes:
            - ./redis_data:/data
        networks:
            - dpf_network
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping" ]
            interval: 10s
            timeout: 8s
            retries: 5
    init-schedule: &base
        build:
            context: .
            dockerfile: docker/.Dockerfile
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - dpf_network
        depends_on:
            - postgres
            - redis
        command: schedule_jobs
    rq-worker:
        <<: *base
        command: worker
        restart: always
    rq-scheduler:
        <<: *base
        command: scheduler
        restart: always

networks:
    dpf_network:
        driver: bridge
        name: dpf_network
