services:
    redis:
        ports:
            - "6379:6379"
    rq-scheduler: &base
        volumes:
            - ./data_processing_framework:/app/data_processing_framework
    rq-worker:
        <<: *base
    rq-dashboard:
        <<: *base
