services:
    # database for jobs and queues
    redis:
        image: redis:latest
        volumes:
            - ./redis_data:/data
        ports:
            - "6379:6379"
        networks:
            - dpf_network
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping" ]
            interval: 10s
            timeout: 8s
            retries: 5
    # worker to run jobs
    rq-worker: &base
        build:
            context: .
            dockerfile: docker/.Dockerfile
        command: worker
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - ./jobs:/app/jobs
        networks:
            - dpf_network
        depends_on:
            - redis
        restart: always
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: vip

    # dashboard to monitor jobs
    rq-dashboard:
        build:
            context: .
            dockerfile: docker/.Dockerfile
        command: dashboard
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        ports:
            - "9181:9181"
        networks:
            - dpf_network
        depends_on:
            - redis
        restart: always

networks:
    dpf_network:
