services:
    # database for jobs and queues
    redis:
        image: redis:latest
        volumes:
            - ./redis_data:/data
        networks:
            - dpf_network
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping" ]
            interval: 10s
            timeout: 8s
            retries: 5

    # job to initially schedule jobs
    rq-scheduler: &base
        build:
            context: .
            dockerfile: docker/.Dockerfile
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        networks:
            - dpf_network
        depends_on:
            - redis
        command: scheduler

    # worker to run jobs
    rq-worker:
        <<: *base
        command: worker
        restart: always
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: vip

    # dashboard to monitor jobs
    rq-dashboard:
        <<: *base
        ports:
            - "9181:9181"
        command: dashboard

networks:
    dpf_network:
