[project]
name = "data-processing-framework"
version = "0.1.0"
description = "Data Processing Framework"
readme = "README.md"
authors = [{ name = "Daniel Kofler", email = "dkofler@outlook.com" }]
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = ["rq>=2.3.3"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F403", "S101"]
select = ["ARG", "C4", "E", "F", "RUF", "S", "SIM", "TC", "W"]
